# Generated by Django 4.2.2 on 2025-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("BrandID", models.AutoField(primary_key=True, serialize=False)),
                ("BrandName", models.CharField(max_length=100)),
                ("LogoURL", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryID", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=100)),
                ("Slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("OrderID", models.AutoField(primary_key=True, serialize=False)),
                ("OrderDate", models.DateTimeField(auto_now_add=True)),
                ("TotalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                ("OrderStatusID", models.AutoField(primary_key=True, serialize=False)),
                ("StatusName", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("PaymentID", models.AutoField(primary_key=True, serialize=False)),
                ("TransactionID", models.CharField(max_length=100, unique=True)),
                ("PaymentMethod", models.CharField(max_length=50)),
                ("PaymentDate", models.DateTimeField(auto_now_add=True)),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PaymentStatus", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("PromotionID", models.AutoField(primary_key=True, serialize=False)),
                ("PromotionName", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "DiscountType",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                ("DiscountValue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("StartDate", models.DateTimeField()),
                ("EndDate", models.DateTimeField()),
                ("IsActive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("Description", models.TextField(blank=True, null=True)),
                ("SKU", models.CharField(max_length=50, unique=True)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("DateAdded", models.DateTimeField(auto_now_add=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True)),
                (
                    "BrandID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminstrator.brand",
                    ),
                ),
                (
                    "CategoryID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminstrator.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("OrderItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.PositiveIntegerField()),
                ("UnitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="adminstrator.order",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminstrator.product",
                    ),
                ),
            ],
        ),
    ]
