# Generated by Django 4.2.2 on 2025-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="BillingAddressID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_orders",
                to="customer.shippingaddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="CustomerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.customer"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="OrderStatusID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminstrator.orderstatus",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="PaymentID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminstrator.payment",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="ShippingAddressID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_orders",
                to="customer.shippingaddress",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="ParentCategoryID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="adminstrator.category",
            ),
        ),
    ]
