# Generated by Django 4.2.2 on 2025-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                ("CourierID", models.AutoField(primary_key=True, serialize=False)),
                ("CourierName", models.CharField(max_length=100)),
                (
                    "ContactEmail",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "ContactPhone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("ShipmentID", models.AutoField(primary_key=True, serialize=False)),
                ("TrackingNumber", models.CharField(max_length=100, unique=True)),
                ("ShipmentDate", models.DateTimeField(auto_now_add=True)),
                ("EstimatedDeliveryDate", models.DateTimeField(blank=True, null=True)),
                ("ActualDeliveryDate", models.DateTimeField(blank=True, null=True)),
                ("ShipmentStatus", models.CharField(max_length=50)),
                (
                    "CourierID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courier.courier",
                    ),
                ),
                (
                    "OrderID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminstrator.order",
                    ),
                ),
            ],
        ),
    ]
