# Generated by Django 4.2.2 on 2025-05-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminstrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=255)),
                ("PhoneNumber", models.CharField(max_length=20)),
                ("RegistrationDate", models.DateTimeField(auto_now_add=True)),
                ("LastLogin", models.DateTimeField(blank=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "ShippingAddressID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("AddressLine1", models.CharField(max_length=100)),
                (
                    "AddressLine2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("City", models.CharField(max_length=50)),
                ("Region", models.CharField(max_length=50)),
                ("PostalCode", models.CharField(max_length=20)),
                ("Country", models.CharField(max_length=50)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("WishlistItemID", models.AutoField(primary_key=True, serialize=False)),
                ("DateAdded", models.DateTimeField(auto_now_add=True)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminstrator.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("CustomerID", "ProductID")},
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("CartItemID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.PositiveIntegerField(default=1)),
                ("DateAdded", models.DateTimeField(auto_now_add=True)),
                (
                    "CustomerID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
                (
                    "ProductID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminstrator.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("CustomerID", "ProductID")},
            },
        ),
    ]
